/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as BajaRouteImport } from './routes/baja'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CotizarRouteImport } from './routes/cotizar'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as PedidoRapidoRouteImport } from './routes/pedido-rapido'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBannersRouteImport } from './routes/admin.banners'
import { Route as AdminCarrinhosRouteImport } from './routes/admin.carrinhos'
import { Route as AdminCatalogosRouteImport } from './routes/admin.catalogos'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminCotacoesRouteImport } from './routes/admin.cotacoes'
import { Route as AdminFotosLoteRouteImport } from './routes/admin.fotos-lote'
import { Route as AdminHomepageRouteImport } from './routes/admin.homepage'
import { Route as AdminInteresseRouteImport } from './routes/admin.interesse'
import { Route as AdminPellegrinoRouteImport } from './routes/admin.pellegrino'
import { Route as AdminPrecificacaoRouteImport } from './routes/admin.precificacao'
import { Route as AdminPrecificarRouteImport } from './routes/admin.precificar'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminUploadRouteImport } from './routes/admin.upload'
import { Route as AdminVisitantesRouteImport } from './routes/admin.visitantes'
import { Route as CatalogosIndexRouteImport } from './routes/catalogos.index'
import { Route as ProdutoSkuRouteImport } from './routes/produto.$sku'
import { Route as UploadsSplatRouteImport } from './routes/uploads.$'
import { Route as AdminEmailsIndexRouteImport } from './routes/admin.emails.index'
import { Route as AdminEmailsIdRouteImport } from './routes/admin.emails.$id'
import { Route as ApiAdminBannersRouteImport } from './routes/api/admin/banners'
import { Route as ApiAdminCategoriesRouteImport } from './routes/api/admin/categories'
import { Route as ApiAdminProductsRouteImport } from './routes/api/admin/products'
import { Route as ApiAdminQuotesRouteImport } from './routes/api/admin/quotes'
import { Route as ApiAuthGoogleRouteImport } from './routes/api/auth.google'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth.login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth.logout'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth.register'
import { Route as ApiPublicAnalyticsRouteImport } from './routes/api/public/analytics'
import { Route as ApiPublicCarrinhoRouteImport } from './routes/api/public/carrinho'
import { Route as ApiPublicEmailBajaRouteImport } from './routes/api/public/email-baja'
import { Route as ApiPublicQuotesRouteImport } from './routes/api/public/quotes'
import { Route as ApiPublicResendWebhookRouteImport } from './routes/api/public/resend-webhook'
import { Route as ApiPublicTrackRouteImport } from './routes/api/public/track'
import { Route as CatalogosArchivoIdRouteImport } from './routes/catalogos.archivo.$id'
import { Route as CatalogosVerIdRouteImport } from './routes/catalogos.ver.$id'
import { Route as ApiAdminBannersIdRouteImport } from './routes/api/admin/banners.$id'
import { Route as ApiAdminBannersUploadRouteImport } from './routes/api/admin/banners.upload'
import { Route as ApiAdminCatalogosUploadRouteImport } from './routes/api/admin/catalogos.upload'
import { Route as ApiAdminCategoriesIdRouteImport } from './routes/api/admin/categories.$id'
import { Route as ApiAdminCategoriesUploadRouteImport } from './routes/api/admin/categories.upload'
import { Route as ApiAdminEmailsUploadRouteImport } from './routes/api/admin/emails.upload'
import { Route as ApiAdminImagesImportRouteImport } from './routes/api/admin/images.import'
import { Route as ApiAdminProductsSkuRouteImport } from './routes/api/admin/products.$sku'
import { Route as ApiAdminProductsExportRouteImport } from './routes/api/admin/products.export'
import { Route as ApiAdminProductsImportRouteImport } from './routes/api/admin/products.import'
import { Route as ApiAdminProductsUploadRouteImport } from './routes/api/admin/products.upload'
import { Route as ApiAdminQuotesIdRouteImport } from './routes/api/admin/quotes.$id'
import { Route as ApiAuthGoogleCallbackRouteImport } from './routes/api/auth.google.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const BajaRoute = BajaRouteImport.update({
  id: '/baja',
  path: '/baja',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizarRoute = CotizarRouteImport.update({
  id: '/cotizar',
  path: '/cotizar',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoRapidoRoute = PedidoRapidoRouteImport.update({
  id: '/pedido-rapido',
  path: '/pedido-rapido',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCarrinhosRoute = AdminCarrinhosRouteImport.update({
  id: '/carrinhos',
  path: '/carrinhos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogosRoute = AdminCatalogosRouteImport.update({
  id: '/catalogos',
  path: '/catalogos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCotacoesRoute = AdminCotacoesRouteImport.update({
  id: '/cotacoes',
  path: '/cotacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFotosLoteRoute = AdminFotosLoteRouteImport.update({
  id: '/fotos-lote',
  path: '/fotos-lote',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInteresseRoute = AdminInteresseRouteImport.update({
  id: '/interesse',
  path: '/interesse',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPellegrinoRoute = AdminPellegrinoRouteImport.update({
  id: '/pellegrino',
  path: '/pellegrino',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrecificacaoRoute = AdminPrecificacaoRouteImport.update({
  id: '/precificacao',
  path: '/precificacao',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPrecificarRoute = AdminPrecificarRouteImport.update({
  id: '/precificar',
  path: '/precificar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVisitantesRoute = AdminVisitantesRouteImport.update({
  id: '/visitantes',
  path: '/visitantes',
  getParentRoute: () => AdminRoute,
} as any)
const CatalogosIndexRoute = CatalogosIndexRouteImport.update({
  id: '/catalogos/',
  path: '/catalogos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSkuRoute = ProdutoSkuRouteImport.update({
  id: '/produto/$sku',
  path: '/produto/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/uploads/$',
  path: '/uploads/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsIndexRoute = AdminEmailsIndexRouteImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsIdRoute = AdminEmailsIdRouteImport.update({
  id: '/emails/$id',
  path: '/emails/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminBannersRoute = ApiAdminBannersRouteImport.update({
  id: '/api/admin/banners',
  path: '/api/admin/banners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesRoute = ApiAdminCategoriesRouteImport.update({
  id: '/api/admin/categories',
  path: '/api/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProductsRoute = ApiAdminProductsRouteImport.update({
  id: '/api/admin/products',
  path: '/api/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminQuotesRoute = ApiAdminQuotesRouteImport.update({
  id: '/api/admin/quotes',
  path: '/api/admin/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGoogleRoute = ApiAuthGoogleRouteImport.update({
  id: '/api/auth/google',
  path: '/api/auth/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyticsRoute = ApiPublicAnalyticsRouteImport.update({
  id: '/api/public/analytics',
  path: '/api/public/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCarrinhoRoute = ApiPublicCarrinhoRouteImport.update({
  id: '/api/public/carrinho',
  path: '/api/public/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailBajaRoute = ApiPublicEmailBajaRouteImport.update({
  id: '/api/public/email-baja',
  path: '/api/public/email-baja',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicQuotesRoute = ApiPublicQuotesRouteImport.update({
  id: '/api/public/quotes',
  path: '/api/public/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicResendWebhookRoute = ApiPublicResendWebhookRouteImport.update({
  id: '/api/public/resend-webhook',
  path: '/api/public/resend-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackRoute = ApiPublicTrackRouteImport.update({
  id: '/api/public/track',
  path: '/api/public/track',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogosArchivoIdRoute = CatalogosArchivoIdRouteImport.update({
  id: '/catalogos/archivo/$id',
  path: '/catalogos/archivo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogosVerIdRoute = CatalogosVerIdRouteImport.update({
  id: '/catalogos/ver/$id',
  path: '/catalogos/ver/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBannersIdRoute = ApiAdminBannersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminBannersRoute,
} as any)
const ApiAdminBannersUploadRoute = ApiAdminBannersUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiAdminBannersRoute,
} as any)
const ApiAdminCatalogosUploadRoute = ApiAdminCatalogosUploadRouteImport.update({
  id: '/api/admin/catalogos/upload',
  path: '/api/admin/catalogos/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesIdRoute = ApiAdminCategoriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminCategoriesRoute,
} as any)
const ApiAdminCategoriesUploadRoute =
  ApiAdminCategoriesUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => ApiAdminCategoriesRoute,
  } as any)
const ApiAdminEmailsUploadRoute = ApiAdminEmailsUploadRouteImport.update({
  id: '/api/admin/emails/upload',
  path: '/api/admin/emails/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminImagesImportRoute = ApiAdminImagesImportRouteImport.update({
  id: '/api/admin/images/import',
  path: '/api/admin/images/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProductsSkuRoute = ApiAdminProductsSkuRouteImport.update({
  id: '/$sku',
  path: '/$sku',
  getParentRoute: () => ApiAdminProductsRoute,
} as any)
const ApiAdminProductsExportRoute = ApiAdminProductsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiAdminProductsRoute,
} as any)
const ApiAdminProductsImportRoute = ApiAdminProductsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiAdminProductsRoute,
} as any)
const ApiAdminProductsUploadRoute = ApiAdminProductsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => ApiAdminProductsRoute,
} as any)
const ApiAdminQuotesIdRoute = ApiAdminQuotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminQuotesRoute,
} as any)
const ApiAuthGoogleCallbackRoute = ApiAuthGoogleCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiAuthGoogleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ayuda': typeof AyudaRoute
  '/baja': typeof BajaRoute
  '/cadastro': typeof CadastroRoute
  '/cotizar': typeof CotizarRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/pedido-rapido': typeof PedidoRapidoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/carrinhos': typeof AdminCarrinhosRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cotacoes': typeof AdminCotacoesRoute
  '/admin/fotos-lote': typeof AdminFotosLoteRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/interesse': typeof AdminInteresseRoute
  '/admin/pellegrino': typeof AdminPellegrinoRoute
  '/admin/precificacao': typeof AdminPrecificacaoRoute
  '/admin/precificar': typeof AdminPrecificarRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/visitantes': typeof AdminVisitantesRoute
  '/produto/$sku': typeof ProdutoSkuRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogos/': typeof CatalogosIndexRoute
  '/admin/emails/$id': typeof AdminEmailsIdRoute
  '/api/admin/banners': typeof ApiAdminBannersRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/products': typeof ApiAdminProductsRouteWithChildren
  '/api/admin/quotes': typeof ApiAdminQuotesRouteWithChildren
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/carrinho': typeof ApiPublicCarrinhoRoute
  '/api/public/email-baja': typeof ApiPublicEmailBajaRoute
  '/api/public/quotes': typeof ApiPublicQuotesRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/catalogos/archivo/$id': typeof CatalogosArchivoIdRoute
  '/catalogos/ver/$id': typeof CatalogosVerIdRoute
  '/admin/emails/': typeof AdminEmailsIndexRoute
  '/api/admin/banners/$id': typeof ApiAdminBannersIdRoute
  '/api/admin/banners/upload': typeof ApiAdminBannersUploadRoute
  '/api/admin/catalogos/upload': typeof ApiAdminCatalogosUploadRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/categories/upload': typeof ApiAdminCategoriesUploadRoute
  '/api/admin/emails/upload': typeof ApiAdminEmailsUploadRoute
  '/api/admin/images/import': typeof ApiAdminImagesImportRoute
  '/api/admin/products/$sku': typeof ApiAdminProductsSkuRoute
  '/api/admin/products/export': typeof ApiAdminProductsExportRoute
  '/api/admin/products/import': typeof ApiAdminProductsImportRoute
  '/api/admin/products/upload': typeof ApiAdminProductsUploadRoute
  '/api/admin/quotes/$id': typeof ApiAdminQuotesIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/baja': typeof BajaRoute
  '/cadastro': typeof CadastroRoute
  '/cotizar': typeof CotizarRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/pedido-rapido': typeof PedidoRapidoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/carrinhos': typeof AdminCarrinhosRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cotacoes': typeof AdminCotacoesRoute
  '/admin/fotos-lote': typeof AdminFotosLoteRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/interesse': typeof AdminInteresseRoute
  '/admin/pellegrino': typeof AdminPellegrinoRoute
  '/admin/precificacao': typeof AdminPrecificacaoRoute
  '/admin/precificar': typeof AdminPrecificarRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/visitantes': typeof AdminVisitantesRoute
  '/produto/$sku': typeof ProdutoSkuRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin': typeof AdminIndexRoute
  '/catalogos': typeof CatalogosIndexRoute
  '/admin/emails/$id': typeof AdminEmailsIdRoute
  '/api/admin/banners': typeof ApiAdminBannersRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/products': typeof ApiAdminProductsRouteWithChildren
  '/api/admin/quotes': typeof ApiAdminQuotesRouteWithChildren
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/carrinho': typeof ApiPublicCarrinhoRoute
  '/api/public/email-baja': typeof ApiPublicEmailBajaRoute
  '/api/public/quotes': typeof ApiPublicQuotesRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/catalogos/archivo/$id': typeof CatalogosArchivoIdRoute
  '/catalogos/ver/$id': typeof CatalogosVerIdRoute
  '/admin/emails': typeof AdminEmailsIndexRoute
  '/api/admin/banners/$id': typeof ApiAdminBannersIdRoute
  '/api/admin/banners/upload': typeof ApiAdminBannersUploadRoute
  '/api/admin/catalogos/upload': typeof ApiAdminCatalogosUploadRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/categories/upload': typeof ApiAdminCategoriesUploadRoute
  '/api/admin/emails/upload': typeof ApiAdminEmailsUploadRoute
  '/api/admin/images/import': typeof ApiAdminImagesImportRoute
  '/api/admin/products/$sku': typeof ApiAdminProductsSkuRoute
  '/api/admin/products/export': typeof ApiAdminProductsExportRoute
  '/api/admin/products/import': typeof ApiAdminProductsImportRoute
  '/api/admin/products/upload': typeof ApiAdminProductsUploadRoute
  '/api/admin/quotes/$id': typeof ApiAdminQuotesIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/ayuda': typeof AyudaRoute
  '/baja': typeof BajaRoute
  '/cadastro': typeof CadastroRoute
  '/cotizar': typeof CotizarRoute
  '/cuenta': typeof CuentaRoute
  '/login': typeof LoginRoute
  '/loja': typeof LojaRoute
  '/pedido-rapido': typeof PedidoRapidoRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/carrinhos': typeof AdminCarrinhosRoute
  '/admin/catalogos': typeof AdminCatalogosRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/cotacoes': typeof AdminCotacoesRoute
  '/admin/fotos-lote': typeof AdminFotosLoteRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/interesse': typeof AdminInteresseRoute
  '/admin/pellegrino': typeof AdminPellegrinoRoute
  '/admin/precificacao': typeof AdminPrecificacaoRoute
  '/admin/precificar': typeof AdminPrecificarRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/visitantes': typeof AdminVisitantesRoute
  '/produto/$sku': typeof ProdutoSkuRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/catalogos/': typeof CatalogosIndexRoute
  '/admin/emails/$id': typeof AdminEmailsIdRoute
  '/api/admin/banners': typeof ApiAdminBannersRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRouteWithChildren
  '/api/admin/products': typeof ApiAdminProductsRouteWithChildren
  '/api/admin/quotes': typeof ApiAdminQuotesRouteWithChildren
  '/api/auth/google': typeof ApiAuthGoogleRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/carrinho': typeof ApiPublicCarrinhoRoute
  '/api/public/email-baja': typeof ApiPublicEmailBajaRoute
  '/api/public/quotes': typeof ApiPublicQuotesRoute
  '/api/public/resend-webhook': typeof ApiPublicResendWebhookRoute
  '/api/public/track': typeof ApiPublicTrackRoute
  '/catalogos/archivo/$id': typeof CatalogosArchivoIdRoute
  '/catalogos/ver/$id': typeof CatalogosVerIdRoute
  '/admin/emails/': typeof AdminEmailsIndexRoute
  '/api/admin/banners/$id': typeof ApiAdminBannersIdRoute
  '/api/admin/banners/upload': typeof ApiAdminBannersUploadRoute
  '/api/admin/catalogos/upload': typeof ApiAdminCatalogosUploadRoute
  '/api/admin/categories/$id': typeof ApiAdminCategoriesIdRoute
  '/api/admin/categories/upload': typeof ApiAdminCategoriesUploadRoute
  '/api/admin/emails/upload': typeof ApiAdminEmailsUploadRoute
  '/api/admin/images/import': typeof ApiAdminImagesImportRoute
  '/api/admin/products/$sku': typeof ApiAdminProductsSkuRoute
  '/api/admin/products/export': typeof ApiAdminProductsExportRoute
  '/api/admin/products/import': typeof ApiAdminProductsImportRoute
  '/api/admin/products/upload': typeof ApiAdminProductsUploadRoute
  '/api/admin/quotes/$id': typeof ApiAdminQuotesIdRoute
  '/api/auth/google/callback': typeof ApiAuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ayuda'
    | '/baja'
    | '/cadastro'
    | '/cotizar'
    | '/cuenta'
    | '/login'
    | '/loja'
    | '/pedido-rapido'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/banners'
    | '/admin/carrinhos'
    | '/admin/catalogos'
    | '/admin/categorias'
    | '/admin/cotacoes'
    | '/admin/fotos-lote'
    | '/admin/homepage'
    | '/admin/interesse'
    | '/admin/pellegrino'
    | '/admin/precificacao'
    | '/admin/precificar'
    | '/admin/produtos'
    | '/admin/upload'
    | '/admin/visitantes'
    | '/produto/$sku'
    | '/uploads/$'
    | '/admin/'
    | '/catalogos/'
    | '/admin/emails/$id'
    | '/api/admin/banners'
    | '/api/admin/categories'
    | '/api/admin/products'
    | '/api/admin/quotes'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/api/public/analytics'
    | '/api/public/carrinho'
    | '/api/public/email-baja'
    | '/api/public/quotes'
    | '/api/public/resend-webhook'
    | '/api/public/track'
    | '/catalogos/archivo/$id'
    | '/catalogos/ver/$id'
    | '/admin/emails/'
    | '/api/admin/banners/$id'
    | '/api/admin/banners/upload'
    | '/api/admin/catalogos/upload'
    | '/api/admin/categories/$id'
    | '/api/admin/categories/upload'
    | '/api/admin/emails/upload'
    | '/api/admin/images/import'
    | '/api/admin/products/$sku'
    | '/api/admin/products/export'
    | '/api/admin/products/import'
    | '/api/admin/products/upload'
    | '/api/admin/quotes/$id'
    | '/api/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayuda'
    | '/baja'
    | '/cadastro'
    | '/cotizar'
    | '/cuenta'
    | '/login'
    | '/loja'
    | '/pedido-rapido'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/banners'
    | '/admin/carrinhos'
    | '/admin/catalogos'
    | '/admin/categorias'
    | '/admin/cotacoes'
    | '/admin/fotos-lote'
    | '/admin/homepage'
    | '/admin/interesse'
    | '/admin/pellegrino'
    | '/admin/precificacao'
    | '/admin/precificar'
    | '/admin/produtos'
    | '/admin/upload'
    | '/admin/visitantes'
    | '/produto/$sku'
    | '/uploads/$'
    | '/admin'
    | '/catalogos'
    | '/admin/emails/$id'
    | '/api/admin/banners'
    | '/api/admin/categories'
    | '/api/admin/products'
    | '/api/admin/quotes'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/api/public/analytics'
    | '/api/public/carrinho'
    | '/api/public/email-baja'
    | '/api/public/quotes'
    | '/api/public/resend-webhook'
    | '/api/public/track'
    | '/catalogos/archivo/$id'
    | '/catalogos/ver/$id'
    | '/admin/emails'
    | '/api/admin/banners/$id'
    | '/api/admin/banners/upload'
    | '/api/admin/catalogos/upload'
    | '/api/admin/categories/$id'
    | '/api/admin/categories/upload'
    | '/api/admin/emails/upload'
    | '/api/admin/images/import'
    | '/api/admin/products/$sku'
    | '/api/admin/products/export'
    | '/api/admin/products/import'
    | '/api/admin/products/upload'
    | '/api/admin/quotes/$id'
    | '/api/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ayuda'
    | '/baja'
    | '/cadastro'
    | '/cotizar'
    | '/cuenta'
    | '/login'
    | '/loja'
    | '/pedido-rapido'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/banners'
    | '/admin/carrinhos'
    | '/admin/catalogos'
    | '/admin/categorias'
    | '/admin/cotacoes'
    | '/admin/fotos-lote'
    | '/admin/homepage'
    | '/admin/interesse'
    | '/admin/pellegrino'
    | '/admin/precificacao'
    | '/admin/precificar'
    | '/admin/produtos'
    | '/admin/upload'
    | '/admin/visitantes'
    | '/produto/$sku'
    | '/uploads/$'
    | '/admin/'
    | '/catalogos/'
    | '/admin/emails/$id'
    | '/api/admin/banners'
    | '/api/admin/categories'
    | '/api/admin/products'
    | '/api/admin/quotes'
    | '/api/auth/google'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/register'
    | '/api/public/analytics'
    | '/api/public/carrinho'
    | '/api/public/email-baja'
    | '/api/public/quotes'
    | '/api/public/resend-webhook'
    | '/api/public/track'
    | '/catalogos/archivo/$id'
    | '/catalogos/ver/$id'
    | '/admin/emails/'
    | '/api/admin/banners/$id'
    | '/api/admin/banners/upload'
    | '/api/admin/catalogos/upload'
    | '/api/admin/categories/$id'
    | '/api/admin/categories/upload'
    | '/api/admin/emails/upload'
    | '/api/admin/images/import'
    | '/api/admin/products/$sku'
    | '/api/admin/products/export'
    | '/api/admin/products/import'
    | '/api/admin/products/upload'
    | '/api/admin/quotes/$id'
    | '/api/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AyudaRoute: typeof AyudaRoute
  BajaRoute: typeof BajaRoute
  CadastroRoute: typeof CadastroRoute
  CotizarRoute: typeof CotizarRoute
  CuentaRoute: typeof CuentaRoute
  LoginRoute: typeof LoginRoute
  LojaRoute: typeof LojaRoute
  PedidoRapidoRoute: typeof PedidoRapidoRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProdutoSkuRoute: typeof ProdutoSkuRoute
  UploadsSplatRoute: typeof UploadsSplatRoute
  CatalogosIndexRoute: typeof CatalogosIndexRoute
  ApiAdminBannersRoute: typeof ApiAdminBannersRouteWithChildren
  ApiAdminCategoriesRoute: typeof ApiAdminCategoriesRouteWithChildren
  ApiAdminProductsRoute: typeof ApiAdminProductsRouteWithChildren
  ApiAdminQuotesRoute: typeof ApiAdminQuotesRouteWithChildren
  ApiAuthGoogleRoute: typeof ApiAuthGoogleRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiPublicAnalyticsRoute: typeof ApiPublicAnalyticsRoute
  ApiPublicCarrinhoRoute: typeof ApiPublicCarrinhoRoute
  ApiPublicEmailBajaRoute: typeof ApiPublicEmailBajaRoute
  ApiPublicQuotesRoute: typeof ApiPublicQuotesRoute
  ApiPublicResendWebhookRoute: typeof ApiPublicResendWebhookRoute
  ApiPublicTrackRoute: typeof ApiPublicTrackRoute
  CatalogosArchivoIdRoute: typeof CatalogosArchivoIdRoute
  CatalogosVerIdRoute: typeof CatalogosVerIdRoute
  ApiAdminCatalogosUploadRoute: typeof ApiAdminCatalogosUploadRoute
  ApiAdminEmailsUploadRoute: typeof ApiAdminEmailsUploadRoute
  ApiAdminImagesImportRoute: typeof ApiAdminImagesImportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baja': {
      id: '/baja'
      path: '/baja'
      fullPath: '/baja'
      preLoaderRoute: typeof BajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizar': {
      id: '/cotizar'
      path: '/cotizar'
      fullPath: '/cotizar'
      preLoaderRoute: typeof CotizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido-rapido': {
      id: '/pedido-rapido'
      path: '/pedido-rapido'
      fullPath: '/pedido-rapido'
      preLoaderRoute: typeof PedidoRapidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/carrinhos': {
      id: '/admin/carrinhos'
      path: '/carrinhos'
      fullPath: '/admin/carrinhos'
      preLoaderRoute: typeof AdminCarrinhosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalogos': {
      id: '/admin/catalogos'
      path: '/catalogos'
      fullPath: '/admin/catalogos'
      preLoaderRoute: typeof AdminCatalogosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cotacoes': {
      id: '/admin/cotacoes'
      path: '/cotacoes'
      fullPath: '/admin/cotacoes'
      preLoaderRoute: typeof AdminCotacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fotos-lote': {
      id: '/admin/fotos-lote'
      path: '/fotos-lote'
      fullPath: '/admin/fotos-lote'
      preLoaderRoute: typeof AdminFotosLoteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/interesse': {
      id: '/admin/interesse'
      path: '/interesse'
      fullPath: '/admin/interesse'
      preLoaderRoute: typeof AdminInteresseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pellegrino': {
      id: '/admin/pellegrino'
      path: '/pellegrino'
      fullPath: '/admin/pellegrino'
      preLoaderRoute: typeof AdminPellegrinoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precificacao': {
      id: '/admin/precificacao'
      path: '/precificacao'
      fullPath: '/admin/precificacao'
      preLoaderRoute: typeof AdminPrecificacaoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/precificar': {
      id: '/admin/precificar'
      path: '/precificar'
      fullPath: '/admin/precificar'
      preLoaderRoute: typeof AdminPrecificarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitantes': {
      id: '/admin/visitantes'
      path: '/visitantes'
      fullPath: '/admin/visitantes'
      preLoaderRoute: typeof AdminVisitantesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/catalogos/': {
      id: '/catalogos/'
      path: '/catalogos'
      fullPath: '/catalogos/'
      preLoaderRoute: typeof CatalogosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$sku': {
      id: '/produto/$sku'
      path: '/produto/$sku'
      fullPath: '/produto/$sku'
      preLoaderRoute: typeof ProdutoSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/uploads/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/emails/': {
      id: '/admin/emails/'
      path: '/emails'
      fullPath: '/admin/emails/'
      preLoaderRoute: typeof AdminEmailsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails/$id': {
      id: '/admin/emails/$id'
      path: '/emails/$id'
      fullPath: '/admin/emails/$id'
      preLoaderRoute: typeof AdminEmailsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/banners': {
      id: '/api/admin/banners'
      path: '/api/admin/banners'
      fullPath: '/api/admin/banners'
      preLoaderRoute: typeof ApiAdminBannersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories': {
      id: '/api/admin/categories'
      path: '/api/admin/categories'
      fullPath: '/api/admin/categories'
      preLoaderRoute: typeof ApiAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/products': {
      id: '/api/admin/products'
      path: '/api/admin/products'
      fullPath: '/api/admin/products'
      preLoaderRoute: typeof ApiAdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/quotes': {
      id: '/api/admin/quotes'
      path: '/api/admin/quotes'
      fullPath: '/api/admin/quotes'
      preLoaderRoute: typeof ApiAdminQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/google': {
      id: '/api/auth/google'
      path: '/api/auth/google'
      fullPath: '/api/auth/google'
      preLoaderRoute: typeof ApiAuthGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics': {
      id: '/api/public/analytics'
      path: '/api/public/analytics'
      fullPath: '/api/public/analytics'
      preLoaderRoute: typeof ApiPublicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/carrinho': {
      id: '/api/public/carrinho'
      path: '/api/public/carrinho'
      fullPath: '/api/public/carrinho'
      preLoaderRoute: typeof ApiPublicCarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-baja': {
      id: '/api/public/email-baja'
      path: '/api/public/email-baja'
      fullPath: '/api/public/email-baja'
      preLoaderRoute: typeof ApiPublicEmailBajaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/quotes': {
      id: '/api/public/quotes'
      path: '/api/public/quotes'
      fullPath: '/api/public/quotes'
      preLoaderRoute: typeof ApiPublicQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/resend-webhook': {
      id: '/api/public/resend-webhook'
      path: '/api/public/resend-webhook'
      fullPath: '/api/public/resend-webhook'
      preLoaderRoute: typeof ApiPublicResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track': {
      id: '/api/public/track'
      path: '/api/public/track'
      fullPath: '/api/public/track'
      preLoaderRoute: typeof ApiPublicTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogos/archivo/$id': {
      id: '/catalogos/archivo/$id'
      path: '/catalogos/archivo/$id'
      fullPath: '/catalogos/archivo/$id'
      preLoaderRoute: typeof CatalogosArchivoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogos/ver/$id': {
      id: '/catalogos/ver/$id'
      path: '/catalogos/ver/$id'
      fullPath: '/catalogos/ver/$id'
      preLoaderRoute: typeof CatalogosVerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/banners/$id': {
      id: '/api/admin/banners/$id'
      path: '/$id'
      fullPath: '/api/admin/banners/$id'
      preLoaderRoute: typeof ApiAdminBannersIdRouteImport
      parentRoute: typeof ApiAdminBannersRoute
    }
    '/api/admin/banners/upload': {
      id: '/api/admin/banners/upload'
      path: '/upload'
      fullPath: '/api/admin/banners/upload'
      preLoaderRoute: typeof ApiAdminBannersUploadRouteImport
      parentRoute: typeof ApiAdminBannersRoute
    }
    '/api/admin/catalogos/upload': {
      id: '/api/admin/catalogos/upload'
      path: '/api/admin/catalogos/upload'
      fullPath: '/api/admin/catalogos/upload'
      preLoaderRoute: typeof ApiAdminCatalogosUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories/$id': {
      id: '/api/admin/categories/$id'
      path: '/$id'
      fullPath: '/api/admin/categories/$id'
      preLoaderRoute: typeof ApiAdminCategoriesIdRouteImport
      parentRoute: typeof ApiAdminCategoriesRoute
    }
    '/api/admin/categories/upload': {
      id: '/api/admin/categories/upload'
      path: '/upload'
      fullPath: '/api/admin/categories/upload'
      preLoaderRoute: typeof ApiAdminCategoriesUploadRouteImport
      parentRoute: typeof ApiAdminCategoriesRoute
    }
    '/api/admin/emails/upload': {
      id: '/api/admin/emails/upload'
      path: '/api/admin/emails/upload'
      fullPath: '/api/admin/emails/upload'
      preLoaderRoute: typeof ApiAdminEmailsUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/images/import': {
      id: '/api/admin/images/import'
      path: '/api/admin/images/import'
      fullPath: '/api/admin/images/import'
      preLoaderRoute: typeof ApiAdminImagesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/products/$sku': {
      id: '/api/admin/products/$sku'
      path: '/$sku'
      fullPath: '/api/admin/products/$sku'
      preLoaderRoute: typeof ApiAdminProductsSkuRouteImport
      parentRoute: typeof ApiAdminProductsRoute
    }
    '/api/admin/products/export': {
      id: '/api/admin/products/export'
      path: '/export'
      fullPath: '/api/admin/products/export'
      preLoaderRoute: typeof ApiAdminProductsExportRouteImport
      parentRoute: typeof ApiAdminProductsRoute
    }
    '/api/admin/products/import': {
      id: '/api/admin/products/import'
      path: '/import'
      fullPath: '/api/admin/products/import'
      preLoaderRoute: typeof ApiAdminProductsImportRouteImport
      parentRoute: typeof ApiAdminProductsRoute
    }
    '/api/admin/products/upload': {
      id: '/api/admin/products/upload'
      path: '/upload'
      fullPath: '/api/admin/products/upload'
      preLoaderRoute: typeof ApiAdminProductsUploadRouteImport
      parentRoute: typeof ApiAdminProductsRoute
    }
    '/api/admin/quotes/$id': {
      id: '/api/admin/quotes/$id'
      path: '/$id'
      fullPath: '/api/admin/quotes/$id'
      preLoaderRoute: typeof ApiAdminQuotesIdRouteImport
      parentRoute: typeof ApiAdminQuotesRoute
    }
    '/api/auth/google/callback': {
      id: '/api/auth/google/callback'
      path: '/callback'
      fullPath: '/api/auth/google/callback'
      preLoaderRoute: typeof ApiAuthGoogleCallbackRouteImport
      parentRoute: typeof ApiAuthGoogleRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCarrinhosRoute: typeof AdminCarrinhosRoute
  AdminCatalogosRoute: typeof AdminCatalogosRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminCotacoesRoute: typeof AdminCotacoesRoute
  AdminFotosLoteRoute: typeof AdminFotosLoteRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminInteresseRoute: typeof AdminInteresseRoute
  AdminPellegrinoRoute: typeof AdminPellegrinoRoute
  AdminPrecificacaoRoute: typeof AdminPrecificacaoRoute
  AdminPrecificarRoute: typeof AdminPrecificarRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminVisitantesRoute: typeof AdminVisitantesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmailsIdRoute: typeof AdminEmailsIdRoute
  AdminEmailsIndexRoute: typeof AdminEmailsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBannersRoute: AdminBannersRoute,
  AdminCarrinhosRoute: AdminCarrinhosRoute,
  AdminCatalogosRoute: AdminCatalogosRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminCotacoesRoute: AdminCotacoesRoute,
  AdminFotosLoteRoute: AdminFotosLoteRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminInteresseRoute: AdminInteresseRoute,
  AdminPellegrinoRoute: AdminPellegrinoRoute,
  AdminPrecificacaoRoute: AdminPrecificacaoRoute,
  AdminPrecificarRoute: AdminPrecificarRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminVisitantesRoute: AdminVisitantesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmailsIdRoute: AdminEmailsIdRoute,
  AdminEmailsIndexRoute: AdminEmailsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAdminBannersRouteChildren {
  ApiAdminBannersIdRoute: typeof ApiAdminBannersIdRoute
  ApiAdminBannersUploadRoute: typeof ApiAdminBannersUploadRoute
}

const ApiAdminBannersRouteChildren: ApiAdminBannersRouteChildren = {
  ApiAdminBannersIdRoute: ApiAdminBannersIdRoute,
  ApiAdminBannersUploadRoute: ApiAdminBannersUploadRoute,
}

const ApiAdminBannersRouteWithChildren = ApiAdminBannersRoute._addFileChildren(
  ApiAdminBannersRouteChildren,
)

interface ApiAdminCategoriesRouteChildren {
  ApiAdminCategoriesIdRoute: typeof ApiAdminCategoriesIdRoute
  ApiAdminCategoriesUploadRoute: typeof ApiAdminCategoriesUploadRoute
}

const ApiAdminCategoriesRouteChildren: ApiAdminCategoriesRouteChildren = {
  ApiAdminCategoriesIdRoute: ApiAdminCategoriesIdRoute,
  ApiAdminCategoriesUploadRoute: ApiAdminCategoriesUploadRoute,
}

const ApiAdminCategoriesRouteWithChildren =
  ApiAdminCategoriesRoute._addFileChildren(ApiAdminCategoriesRouteChildren)

interface ApiAdminProductsRouteChildren {
  ApiAdminProductsSkuRoute: typeof ApiAdminProductsSkuRoute
  ApiAdminProductsExportRoute: typeof ApiAdminProductsExportRoute
  ApiAdminProductsImportRoute: typeof ApiAdminProductsImportRoute
  ApiAdminProductsUploadRoute: typeof ApiAdminProductsUploadRoute
}

const ApiAdminProductsRouteChildren: ApiAdminProductsRouteChildren = {
  ApiAdminProductsSkuRoute: ApiAdminProductsSkuRoute,
  ApiAdminProductsExportRoute: ApiAdminProductsExportRoute,
  ApiAdminProductsImportRoute: ApiAdminProductsImportRoute,
  ApiAdminProductsUploadRoute: ApiAdminProductsUploadRoute,
}

const ApiAdminProductsRouteWithChildren =
  ApiAdminProductsRoute._addFileChildren(ApiAdminProductsRouteChildren)

interface ApiAdminQuotesRouteChildren {
  ApiAdminQuotesIdRoute: typeof ApiAdminQuotesIdRoute
}

const ApiAdminQuotesRouteChildren: ApiAdminQuotesRouteChildren = {
  ApiAdminQuotesIdRoute: ApiAdminQuotesIdRoute,
}

const ApiAdminQuotesRouteWithChildren = ApiAdminQuotesRoute._addFileChildren(
  ApiAdminQuotesRouteChildren,
)

interface ApiAuthGoogleRouteChildren {
  ApiAuthGoogleCallbackRoute: typeof ApiAuthGoogleCallbackRoute
}

const ApiAuthGoogleRouteChildren: ApiAuthGoogleRouteChildren = {
  ApiAuthGoogleCallbackRoute: ApiAuthGoogleCallbackRoute,
}

const ApiAuthGoogleRouteWithChildren = ApiAuthGoogleRoute._addFileChildren(
  ApiAuthGoogleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AyudaRoute: AyudaRoute,
  BajaRoute: BajaRoute,
  CadastroRoute: CadastroRoute,
  CotizarRoute: CotizarRoute,
  CuentaRoute: CuentaRoute,
  LoginRoute: LoginRoute,
  LojaRoute: LojaRoute,
  PedidoRapidoRoute: PedidoRapidoRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProdutoSkuRoute: ProdutoSkuRoute,
  UploadsSplatRoute: UploadsSplatRoute,
  CatalogosIndexRoute: CatalogosIndexRoute,
  ApiAdminBannersRoute: ApiAdminBannersRouteWithChildren,
  ApiAdminCategoriesRoute: ApiAdminCategoriesRouteWithChildren,
  ApiAdminProductsRoute: ApiAdminProductsRouteWithChildren,
  ApiAdminQuotesRoute: ApiAdminQuotesRouteWithChildren,
  ApiAuthGoogleRoute: ApiAuthGoogleRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiPublicAnalyticsRoute: ApiPublicAnalyticsRoute,
  ApiPublicCarrinhoRoute: ApiPublicCarrinhoRoute,
  ApiPublicEmailBajaRoute: ApiPublicEmailBajaRoute,
  ApiPublicQuotesRoute: ApiPublicQuotesRoute,
  ApiPublicResendWebhookRoute: ApiPublicResendWebhookRoute,
  ApiPublicTrackRoute: ApiPublicTrackRoute,
  CatalogosArchivoIdRoute: CatalogosArchivoIdRoute,
  CatalogosVerIdRoute: CatalogosVerIdRoute,
  ApiAdminCatalogosUploadRoute: ApiAdminCatalogosUploadRoute,
  ApiAdminEmailsUploadRoute: ApiAdminEmailsUploadRoute,
  ApiAdminImagesImportRoute: ApiAdminImagesImportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
